name: Auto Deploy to DirectAdmin cPanel (3-Second Fast)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Direct to cPanel
        run: |
          python deploy_script.py
